<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('My Cookbook')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/animate.css')
        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Lato:100,300,400')
        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css') ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/ember/ember.js')
        ->prependFile($this->basePath() . '/ember/handlebars.js')
        ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<script type="text/x-handlebars" id="index">
    <nav class="navbar navbar-default navbar-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">My Cookbook</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right" style="">
                    <li class="active"><a href="#home">Home</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">
        <?php echo $this->content; ?>
    </div>
    <footer class="footer navbar-fixed-bottom">
        <div class="legal">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <p>&copy; <?php echo date('Y') ?> By Juan Jardim. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>




</script>
<?php echo $this->inlineScript()
    ->appendFile('/ember/App/Views/MainView.js')
    ->appendFile('/ember/App/Controllers/App.js')
    ->appendFile('/ember/App/Controllers/FactoryController.js')
    ->appendFile('/ember/App/Controllers/RepositoryController.js')
    ->appendFile('/ember/library.js'); ?>

</body>
</html>
