<footer id="about">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="headline"><h3>About</h3></div>
                <div class="content">
                    <p>
                        This site was made with the purpose of learning new technologies and put them into practice. For this reason, this site is just a demonstration of my work. If you want to help me to put this site alive, please contact me. Thank you for visiting.
                    </p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="headline"><h3>Go Social</h3></div>
                <div class="content social">
                    <p>Stay in touch with us:</p>
                    <!--<ul>
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-pinterest"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-youtube"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-github"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-vk"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a>
                    </li>
                </ul>-->
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="headline"><h3>Contact us</h3></div>
                <div class="content">
                    <p>
                        Email: <a href="#">juanjardim@hotmail.com</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>
<div class="legal">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p>&copy; <?php echo date('Y') ?> By Juan Jardim. All rights reserved.</p>
            </div>
        </div>
    </div>
</div>
